---
deployment:
  tasks:
    - export DEPLOYPATH=/home/weekwfyz/public_html
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
