const Teachers = [
  {
    firstName: "Kate",
    lastName: "Nate",
    age: 38,
    phonenumber: 123456789123,
    weeklyhours: 36,
    email: "Kate@gmail.com",
  },
  {
    firstName: "Fred",
    lastName: "Bread",
    age: 29,
    phonenumber: 98745612,
    weeklyhours: 36,
    email: "Fred@gmail.com",
  },
  {
    firstName: "Ramesh",
    lastName: "Babu",
    age: 35,
    phonenumber: 123456789,
    weeklyhours: 36,
    email: "babu@xyz.com",
  },
  {
    firstName: "Gerry",
    lastName: "Sun",
    age: 49,
    phonenumber: 3456789123,
    weeklyhours: 30,
    email: "Gerry@gmail.com",
  },
  {
    firstName: "Lemmy",
    lastName: "Kobe",
    age: 34,
    phonenumber: 6985664166,
    weeklyhours: 35,
    email: "Lemmy@gmail.com",
  },
  {
    firstName: "Aiden",
    lastName: "Freddy",
    age: 31,
    phonenumber: 369852147,
    weeklyhours: 36,
    email: "Aiden@gmail.com",
  },
];
